version: "3.9"

services:
  astro:
    container_name: ape-agent-dev
    build:
      context: agent
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./agent:/app
    environment:
      NODE_ENV: development
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}

    command: bun run dev -- --host
