/**
 * @file chat.ts
 * @description
 * Domain types for the AI Portfolio Decision Co-Pilot (Automated Portfolio Evaluator) chat protocol.
 *
 * This file defines the canonical request/response shapes used between UI and API.
 * Keeping these in one place prevents "UI shapes the protocol" drift.
 */

/**
 * A supported chat role for multi-turn conversation.
 */
export type ChatRole = "user" | "assistant" | "system";

/**
 * A single chat message in a multi-turn conversation.
 */
export interface ChatMessage {
  /**
   * The role of the message sender.
   */
  role: ChatRole;

  /**
   * The message content.
   */
  content: string;
}

/**
 * Request payload sent by the UI to the API.
 */
export interface ChatRequest {
  /**
   * Full conversation history, in order.
   * The service may apply truncation or limits as needed.
   */
  messages: ChatMessage[];
}

/**
 * Response payload returned by the API to the UI.
 */
export interface ChatResponse {
  /**
   * The assistant message generated by the agent.
   */
  assistant: {
    /**
     * Assistant content. Plain text for Milestone #1.
     */
    content: string;
  };
}
